# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Actions:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
       
    - name: Build with Maven
      run: mvn package -Pstandard-coverage --no-transfer-progress

    - name: Save Jacoco Report
      uses: actions/upload-artifact@v3
      with:
        name: 1-Jacoco Report
        path: storm-client/target/site/jacoco

    - name: Save Pit Report
      uses: actions/upload-artifact@v3
      with:
        name: 2-Pit Report
        path: storm-client/target/pit-reports

    # Ba-Dua doesn't work well with junit5
    #- name: Change Permissions for Ba-Dua
    #  run: chmod +x dfc/report.sh

    #- name: Build for Ba-Dua Report
    #  run: mvn package -Pba-dua-coverage --no-transfer-progress
     
    #- name: Save Ba-Dua Report
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: 3-Ba-Dua Report
    #    path: storm-client/target/badua.xml
